# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title:  Breaking changes
      labels: [ breaking-change ]

    - title: 󱓞 New features
      labels: [ enhancement ]

    - title: 󱁤 Refactors and bug fixes
      labels: [ bug, refactor ]
