name: "CI"

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, develop ]
    paths: [ contracts, test ]


jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ^8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run test suite
        run: pnpm hardhat test

      - name: Run checks
        run: pnpm hardhat check
