
name: Publish package to GitHub Packages
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@fusyona"
            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8.6.7
            - run: pnpm install
            - name: Publish package
              run: |
                  if ${{ github.event.release.prerelease }}; then
                      pnpm publish --tag beta --no-git-checks
                  else
                      pnpm publish --no-git-checks
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}