name: Publish package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ^8

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
          scope: "@fusyona"

      - run: pnpm install
      - name: Publish package
        run: |
          if ${{ github.event.release.prerelease }}; then
              pnpm publish --tag beta --no-git-checks
          else
              pnpm publish --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
